import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import RefreshToken from "./actions/refreshToken";
import { useMemo } from "react";
import { AuthProvider } from "./context/AuthProvider";
import { SearchFunctionsProvider } from "./context/SearchProvider ";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Return",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-medium bg-[#f0f2f5]`}>
        <Providers>
          <AuthProvider>
            <SearchFunctionsProvider>{children}</SearchFunctionsProvider>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
